### ISSUE TITLE
Missing course of COMP2420

### ISSUE THREAD

**Issue by pl4nty** [pl4nty/anutimetable#389] opened 2024-01-26 13:55 UTC
Please add the course COMP2420 on the timetable. I am not able to make the timetable for the upcoming semester of 2024.

Label: Missing course

_Originally submitted by anonymous via the Microsoft Form_

**Comment by jthvai** [comment] 2024-01-26 14:04
Duplicate of #377.

**Closed by jthvai** 2024-01-26 14:04 UTC
