### ISSUE TITLE
Timetable only shows until 2pm

### ISSUE THREAD

**Issue by pl4nty** [pl4nty/anutimetable#358] opened 2023-12-13 11:15 UTC
When I open the timetable it only shows the times from 6am to 2pm

Label: Issue

_Originally submitted by anonymous via the Microsoft Form_

**Comment by jthvai** [comment] 2024-01-09 07:30
The timetable normally only displays 9am-6pm. It displays 6am-3pm if the timezone is set to SYD minus 3 hours (Perth during summer), manually in the timetable's interface. The timezone of the computer or the location of the connection seems to have no bearing on this. 

Closing as intended behaviour. Please reopen if the timezone was actually set to "Canberra, Melbourne, Sydney" in the original report.

**Closed by jthvai** 2024-01-09 07:30 UTC
